---
burpsuite_extensions_pro:
  - name: "Error Message Checks"
    bapp_uuid: "4f01db4b668c4126a68e4673df796f0f"
    bapp_serial_version: "13"
    type: "java"
    use_ai: false
    loaded: true
  - name: "Retire.js"
    bapp_uuid: "36238b534a78494db9bf2d03f112265c"
    bapp_serial_version: "13"
    type: "java"
    use_ai: false
    loaded: true
  - name: "Software Vulnerability Scanner"
    bapp_uuid: "c9fb79369b56407792a7104e3c4352fb"
    bapp_serial_version: "7"
    type: "java"
    use_ai: false
    loaded: true
  - name: "Software Version Reporter"
    bapp_uuid: "ae62baff8fa24150991bad5eaf6d4d38"
    bapp_serial_version: "15"
    type: "java"
    use_ai: false
    loaded: true
  - name: "JS Miner"
    bapp_uuid: "0ab7a94d8e11449daaf0fb387431225b"
    bapp_serial_version: "8"
    type: "java"
    use_ai: false
    loaded: true
  - name: "SRI Check"
    bapp_uuid: "2e3a9895bb9b41f8b8a1193ec0399d3d"
    bapp_serial_version: "1"
    type: "python"
    use_ai: false
    loaded: true
  - name: "URL Fuzzer - 401/403 Bypass"
    bapp_uuid: "89f689c69d3840e99d73eacaff3e4a8d"
    bapp_serial_version: "1"
    type: "java"
    use_ai: false
    loaded: false
  - name: "Active Scan++"
    bapp_uuid: "3123d5b5f25c4128894d97ea1acc4976"
    bapp_serial_version: "39"
    type: "java"
    use_ai: false
    loaded: true
  - name: "Additional Scanner Checks"
    bapp_uuid: "a158fd3fc9394253be3aa0bc4c181d1f"
    bapp_serial_version: "6"
    type: "python"
    use_ai: false
    loaded: true
  - name: "Backslash Powered Scanner"
    bapp_uuid: "9cff8c55432a45808432e26dbb2b41d8"
    bapp_serial_version: "28"
    type: "java"
    use_ai: false
    loaded: true
  - name: "CSRF Scanner"
    bapp_uuid: "60f172f27a9b49a1b538ed414f9f27c3"
    bapp_serial_version: "6"
    type: "java"
    use_ai: false
    loaded: true
  - name: "Collaborator Everywhere"
    bapp_uuid: "2495f6fb364d48c3b6c984e226c02968"
    bapp_serial_version: "5"
    type: "java"
    use_ai: false
    loaded: false
