common_pkgs:
  apt:
    install:
      - 7zip
      - bc
      - enum4linux
      - jq
      - kali-themes
      - keepassxc
      - libimage-exiftool-perl
      - libreoffice
      - lightdm
      - maven
      - metasploit-framework
      - netexec
      - network-manager-applet
      - network-manager-openconnect-gnome
      - nmap
      - openconnect
      - openvpn
      - pipx
      - pulsemixer
      - python3-venv
      - qt5ct
      - qt6ct
      - ripgrep
      - rsync
      - seclists
      - smbclient
      - usbutils
      - wafw00f
      - wireplumber
      - wireshark
      - xclip
      - xxd
      - zip
      - zoxide
      # mobile pentesting
      - adb
      - libimobiledevice-utils
      - libusbmuxd-tools
      - qrencode
      - sqlitebrowser
      - usbmuxd
      - wireless-tools
      # embedded pentesting
      - arping
      - macchanger
    remove: []
    remove_regex: []
    remove_modified_configs: false
