---
common_pkgs_apt:
  install:
    - 7zip
    - bc
    - enum4linux
    - jq
    - kali-themes
    # - keepassxc
    - libimage-exiftool-perl
    - libreoffice
    - lightdm
    - maven
    - metasploit-framework
    - netexec
    - name: network-manager-applet
      depends:
        - lxpolkit
    - network-manager-openconnect-gnome
    - nmap
    - openconnect
    - openvpn
    - pipx
    - pulsemixer
    - qt5ct
    - qt6ct
    - ripgrep
    - rsync
    - seclists
    - smbclient
    - usbutils
    - wafw00f
    - wireplumber
    - wireshark
    - xclip
    - xxd
    - zip
    - zoxide
    # mobile pentesting
    - adb
    - libimobiledevice-utils
    - libusbmuxd-tools
    - qrencode
    - sqlitebrowser
    - usbmuxd
    - wireless-tools
    # iot/ot pentesting
    - arping
    - macchanger
    - isc-dhcp-client
    - hping3
  remove: []
  remove_regex: []
  remove_modified_configs: false
