---
golang_tools:
  - name: "github.com/tomnomnom/gf"
    version: "dcd4c361f9f5ba302294ed38b8ce278e8ba69006"
  - name: "github.com/tomnomnom/fff"
    version: "544f7e5983ec81119bf24dc3d98fc45f9667665a"
  - name: "github.com/tomnomnom/anew"
    version: "d67d68db0d56469fdea7505c5a9209c0a465effa"
  - name: "github.com/tomnomnom/assetfinder"
    version: "4e95d8701aae8cff1c27af2626eb22ba110ad583"
  - name: "github.com/tomnomnom/httprobe"
    version: "0745f649beb01c3cf712e0c52f9760d8a92cfdc2"
  - name: "github.com/ffuf/ffuf/v2"
    version: "de9ac86677818de0743d8db24147c81c96b73a74"
  - name: "github.com/projectdiscovery/nuclei/v3/cmd/nuclei"
    version: "v3.3.10"
  - name: "github.com/neex/ghostinthepdf"
    version: "e7ff1963b86f262a12f411c79dfdd7f32132021f"
  - name: "github.com/BishopFox/jsluice/cmd/jsluice"
    version: "0ddfab153e060a9eeaded4d8669233f7c071e7e4"
  - name: "github.com/rverton/webanalyze/cmd/webanalyze"
    version: "v0.4.1"
  - name: "github.com/bitquark/shortscan/cmd/shortscan"
    version: "v0.9.2"
  - name: "github.com/assetnote/kiterunner/cmd/kiterunner"
    version: "v1.0.2"
  - name: "github.com/xonoxitron/regreSSHion-checker"
    version: "ae73f5ff39490930fe4d730964121a9c3aa7e7b2"
