---
tigervnc_users:
  - username: "{{ ansible_user }}"
    display: 4
    password: ""
    session_command: "/usr/bin/i3"
    localhost: true
    securitytypes: "none"
    alwaysshared: true
    service_enabled: true
