##################################################################################
# SOURCES
##################################################################################

# Source 1: Base image (boots from ISO)
source "qemu" "kali-linux-base" {
  vm_name          = "${local.vm_name}.qcow2"
  iso_url          = local.kali_iso_url_x86_64
  iso_checksum     = local.kali_iso_checksum_x86_64
  iso_target_path  = "${path.root}/${var.packer_input_dir}/${local.kali_iso_name_x86_64}"
  http_directory   = local.http_directory
  http_interface   = var.http_interface
  shutdown_command = local.vm_nonroot_shutdown_command
  ssh_username     = var.vm_ssh_username
  ssh_password     = var.vm_ssh_temp_password
  ssh_timeout      = var.vm_ssh_timeout
  ssh_port         = var.vm_ssh_port
  boot_command     = local.debian_boot_command_x86_64
  boot_wait        = var.vm_boot_wait
  disk_size        = "${var.vm_disk_size}M"
  disk_interface   = var.qemu_disk_interface
  net_device       = var.qemu_net_device
  format           = var.qemu_format
  accelerator      = var.qemu_accelerator
  machine_type     = var.qemu_machine_type
  cpus             = var.vm_cpu_core
  memory           = var.vm_mem_size
  display          = var.qemu_display
  headless         = var.qemu_headless
  output_directory = "${local.base_packer_output}"
  qemuargs = [
    ["-bios", "/usr/share/edk2-ovmf/x64/OVMF.4m.fd"]
  ]
}

# Source 2: QEMU build (boots from base qcow2)
source "qemu" "kali-linux-qemu" {
  vm_name          = "${local.vm_name}.qcow2"
  disk_image       = true
  iso_url          = "${local.base_packer_output}/${local.vm_name}.qcow2"
  # Checksum file is auto-generated by base build post-processor
  iso_checksum     = "file:${local.base_packer_output}/${local.vm_name}.qcow2.sha256"
  shutdown_command = local.vm_nonroot_shutdown_command
  ssh_username     = var.vm_ssh_username
  ssh_password     = var.vm_ssh_password
  ssh_timeout      = var.vm_ssh_timeout
  ssh_port         = var.vm_ssh_port
  boot_wait        = "5s"
  disk_size        = "${var.vm_disk_size}M"
  disk_interface   = var.qemu_disk_interface
  net_device       = var.qemu_net_device
  format           = var.qemu_format
  accelerator      = var.qemu_accelerator
  machine_type     = var.qemu_machine_type
  cpus             = var.vm_cpu_core
  memory           = var.vm_mem_size
  display          = var.qemu_display
  headless         = var.qemu_headless
  output_directory = "${local.qemu_packer_output}"
  qemuargs = [
    ["-bios", "/usr/share/edk2-ovmf/x64/OVMF.4m.fd"]
  ]
}

# Source 3: VirtualBox build (boots from base qcow2)
source "qemu" "kali-linux-virtualbox" {
  vm_name          = "${local.vm_name}.qcow2"
  disk_image       = true
  iso_url          = "${local.base_packer_output}/${local.vm_name}.qcow2"
  # Checksum file is auto-generated by base build post-processor
  iso_checksum     = "file:${local.base_packer_output}/${local.vm_name}.qcow2.sha256"
  shutdown_command = local.vm_nonroot_shutdown_command
  ssh_username     = var.vm_ssh_username
  ssh_password     = var.vm_ssh_password
  ssh_timeout      = var.vm_ssh_timeout
  ssh_port         = var.vm_ssh_port
  boot_wait        = "5s"
  disk_size        = "${var.vm_disk_size}M"
  disk_interface   = var.qemu_disk_interface
  net_device       = var.qemu_net_device
  format           = var.qemu_format
  accelerator      = var.qemu_accelerator
  machine_type     = var.qemu_machine_type
  cpus             = var.vm_cpu_core
  memory           = var.vm_mem_size
  display          = var.qemu_display
  headless         = var.qemu_headless
  output_directory = "${local.virtualbox_packer_output}"
  qemuargs = [
    ["-bios", "/usr/share/edk2-ovmf/x64/OVMF.4m.fd"]
  ]
}

# Source 4: VMware build (boots from base qcow2)
source "qemu" "kali-linux-vmware" {
  vm_name          = "${local.vm_name}.qcow2"
  disk_image       = true
  iso_url          = "${local.base_packer_output}/${local.vm_name}.qcow2"
  # Checksum file is auto-generated by base build post-processor
  iso_checksum     = "file:${local.base_packer_output}/${local.vm_name}.qcow2.sha256"
  shutdown_command = local.vm_nonroot_shutdown_command
  ssh_username     = var.vm_ssh_username
  ssh_password     = var.vm_ssh_password
  ssh_timeout      = var.vm_ssh_timeout
  ssh_port         = var.vm_ssh_port
  boot_wait        = "5s"
  disk_size        = "${var.vm_disk_size}M"
  disk_interface   = var.qemu_disk_interface
  net_device       = var.qemu_net_device
  format           = var.qemu_format
  accelerator      = var.qemu_accelerator
  machine_type     = var.qemu_machine_type
  cpus             = var.vm_cpu_core
  memory           = var.vm_mem_size
  display          = var.qemu_display
  headless         = var.qemu_headless
  output_directory = "${local.vmware_packer_output}"
  qemuargs = [
    ["-bios", "/usr/share/edk2-ovmf/x64/OVMF.4m.fd"]
  ]
}



##################################################################################
# BUILDS
##################################################################################

# Build 1: Base image (no guest utilities)
build {
  name = "base"

  sources = [
    "source.qemu.kali-linux-base"
  ]

  provisioner "breakpoint" {
    disable = true
    note    = "Breakpoint before ansible run"
  }

  provisioner "ansible" {
    collections_path = "${path.root}/${var.ansible_collections_path}"
    roles_path       = "${path.root}/${var.ansible_roles_path}"
    playbook_file    = "${path.root}/${var.ansible_playbook_init}"
    user             = "${var.vm_ssh_username}"
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
      "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
      "ANSIBLE_FORCE_COLOR=true",
      "ANSIBLE_HOST_KEY_CHECKING=false",
    ]
    extra_arguments = [
      "--extra-vars",
      "ansible_become_password=${var.vm_ssh_temp_password}",
    ]
  }

  provisioner "ansible" {
    collections_path = "${path.root}/${var.ansible_collections_path}"
    roles_path       = "${path.root}/${var.ansible_roles_path}"
    playbook_file    = "${path.root}/${var.ansible_playbook_base}"
    user             = "${var.vm_ssh_username}"
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
      "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
      "ANSIBLE_FORCE_COLOR=true",
      "ANSIBLE_HOST_KEY_CHECKING=false",
    ]
    extra_arguments = [
      "--extra-vars",
      "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
    ]
  }

  provisioner "breakpoint" {
    disable = true
    note    = "Breakpoint after ansible run"
  }

  # Post-processor: Generate checksum file for downstream builds
  # This checksum is referenced by sources 2-4 (QEMU, VirtualBox, VMware)
  post-processor "shell-local" {
    inline = [
      "set -e",
      "cd ${local.base_packer_output}",
      "sha256sum ${local.vm_name}.qcow2 > ${local.vm_name}.qcow2.sha256",
      "test -f ${local.vm_name}.qcow2.sha256 || exit 1",
      "echo 'Generated checksum file: ${local.vm_name}.qcow2.sha256'",
      "cat ${local.vm_name}.qcow2.sha256"
    ]
  }

}

# Build 2: QEMU image (with QEMU guest agent)
build {
  name = "qemu"

  sources = [
    "source.qemu.kali-linux-qemu"
  ]

  # provisioner "ansible" {
  #   collections_path = "${path.root}/${var.ansible_collections_path}"
  #   roles_path       = "${path.root}/${var.ansible_roles_path}"
  #   playbook_file    = "${path.root}/${var.ansible_playbook_qemu}"
  #   user             = "${var.vm_ssh_username}"
  #   ansible_env_vars = [
  #     "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
  #     "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
  #     "ANSIBLE_FORCE_COLOR=true",
  #     "ANSIBLE_HOST_KEY_CHECKING=false",
  #   ]
  #   extra_arguments = [
  #     "--extra-vars",
  #     "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
  #   ]
  # }

  provisioner "ansible" {
    collections_path = "${path.root}/${var.ansible_collections_path}"
    roles_path       = "${path.root}/${var.ansible_roles_path}"
    playbook_file    = "${path.root}/${var.ansible_playbook_finalize}"
    user             = "${var.vm_ssh_username}"
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
      "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
      "ANSIBLE_FORCE_COLOR=true",
      "ANSIBLE_HOST_KEY_CHECKING=false",
    ]
    extra_arguments = [
      "--extra-vars",
      "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
    ]
  }

}

# Build 3: VirtualBox image (with VirtualBox guest additions)
build {
  name = "virtualbox"

  sources = [
    "source.qemu.kali-linux-virtualbox"
  ]

  provisioner "ansible" {
    collections_path = "${path.root}/${var.ansible_collections_path}"
    roles_path       = "${path.root}/${var.ansible_roles_path}"
    playbook_file    = "${path.root}/${var.ansible_playbook_virtualbox}"
    user             = "${var.vm_ssh_username}"
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
      "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
      "ANSIBLE_FORCE_COLOR=true",
      "ANSIBLE_HOST_KEY_CHECKING=false",
    ]
    extra_arguments = [
      "--extra-vars",
      "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
    ]
  }

  provisioner "ansible" {
    collections_path = "${path.root}/${var.ansible_collections_path}"
    roles_path       = "${path.root}/${var.ansible_roles_path}"
    playbook_file    = "${path.root}/${var.ansible_playbook_finalize}"
    user             = "${var.vm_ssh_username}"
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
      "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
      "ANSIBLE_FORCE_COLOR=true",
      "ANSIBLE_HOST_KEY_CHECKING=false",
    ]
    extra_arguments = [
      "--extra-vars",
      "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
    ]
  }

  # Post-processors: Convert to VirtualBox format
  post-processors {
    # Step 1: Convert QEMU qcow2 to VirtualBox VMDK
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Converting qcow2 to VirtualBox VMDK format...'",
        "mkdir -p ${local.virtualbox_output_path}",
        "qemu-img convert -f qcow2 -O vmdk -o subformat=streamOptimized ${local.virtualbox_packer_output}/${local.vm_name}.qcow2 ${local.virtualbox_output_path}/${local.vm_name}.vmdk",
        "test -f ${local.virtualbox_output_path}/${local.vm_name}.vmdk || exit 1",
        "echo 'VMDK conversion complete'",
        "# Delete qcow2 to save space",
        "rm -rf ${local.virtualbox_packer_output}"
      ]
    }

    # Step 2: Register VMDK as artifact
    post-processor "artifice" {
      files = [
        "${local.virtualbox_output_path}/${local.vm_name}.vmdk"
      ]
      keep_input_artifact = false
    }

    # Step 3: Generate OVF file
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Generating VirtualBox OVF descriptor...'",
        "cd ${local.virtualbox_output_path}",
        <<-EOT
        cat > ${local.vm_name}.ovf <<'OVFEOF'
        ${templatefile("templates/virtualbox.ovf.pkrtpl.hcl", {
          vm_name                  = local.vm_name
          vm_disk_size             = var.vm_disk_size
          vm_cpu_core              = var.vm_cpu_core
          vm_mem_size              = var.vm_mem_size
          vbox_graphics_controller = var.vbox_graphics_controller
          vbox_vram                = var.vbox_vram
          vbox_accelerate_3d       = var.vbox_accelerate_3d
          vbox_firmware_type       = upper(var.vbox_firmware_type)
          vbox_clipboard_mode      = title(var.vbox_clipboard_mode)
        })}
        OVFEOF
        EOT
        ,
        "test -f ${local.vm_name}.ovf || exit 1",
        "echo 'OVF descriptor created successfully'"
      ]
    }

    # Step 4: Register both VMDK and OVF as artifacts
    post-processor "artifice" {
      files = [
        "${local.virtualbox_output_path}/${local.vm_name}.vmdk",
        "${local.virtualbox_output_path}/${local.vm_name}.ovf"
      ]
      keep_input_artifact = true
    }

    # Step 5: Create Vagrant .box file
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Creating Vagrant VirtualBox box...'",
        "mkdir -p ${local.vagrant_output_path}",
        "test -f ${local.virtualbox_output_path}/${local.vm_name}.vmdk || exit 1",
        "test -f ${local.virtualbox_output_path}/${local.vm_name}.ovf || exit 1",
        "echo '{\"provider\":\"virtualbox\"}' > ${local.vagrant_output_path}/metadata.json",
        "tar czf ${local.vagrant_output_path}/${local.vm_name}-virtualbox.box -C ${local.virtualbox_output_path} ${local.vm_name}.vmdk ${local.vm_name}.ovf -C ${local.vagrant_output_path} metadata.json",
        "test -f ${local.vagrant_output_path}/${local.vm_name}-virtualbox.box || exit 1",
        "echo 'Vagrant box created: ${local.vm_name}-virtualbox.box'",
        "rm -f ${local.vagrant_output_path}/metadata.json"
      ]
    }
  }
}

# Build 4: VMware image (with VMware tools)
build {
  name = "vmware"

  sources = [
    "source.qemu.kali-linux-vmware"
  ]

  # provisioner "ansible" {
  #   collections_path = "${path.root}/${var.ansible_collections_path}"
  #   roles_path       = "${path.root}/${var.ansible_roles_path}"
  #   playbook_file    = "${path.root}/${var.ansible_playbook_vmware}"
  #   user             = "${var.vm_ssh_username}"
  #   ansible_env_vars = [
  #     "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
  #     "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
  #     "ANSIBLE_FORCE_COLOR=true",
  #     "ANSIBLE_HOST_KEY_CHECKING=false",
  #   ]
  #   extra_arguments = [
  #     "--extra-vars",
  #     "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
  #   ]
  # }

  provisioner "ansible" {
    collections_path = "${path.root}/${var.ansible_collections_path}"
    roles_path       = "${path.root}/${var.ansible_roles_path}"
    playbook_file    = "${path.root}/${var.ansible_playbook_finalize}"
    user             = "${var.vm_ssh_username}"
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=${path.root}/${var.ansible_roles_path}",
      "ANSIBLE_VAULT_PASSWORD_FILE=${path.root}/${var.ansible_vault_password_file}",
      "ANSIBLE_FORCE_COLOR=true",
      "ANSIBLE_HOST_KEY_CHECKING=false",
    ]
    extra_arguments = [
      "--extra-vars",
      "ansible_become_password=${var.vm_ssh_password} ansible_remote_tmp=/tmp ",
    ]
  }

  # Post-processors: Convert to VMware format
  post-processors {
    # Step 1: Convert QEMU qcow2 to VMware VMDK
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Converting qcow2 to VMware VMDK format...'",
        "mkdir -p ${local.vmware_output_path}",
        "qemu-img convert -f qcow2 -O vmdk -o subformat=streamOptimized ${local.vmware_packer_output}/${local.vm_name}.qcow2 ${local.vmware_output_path}/${local.vm_name}.vmdk",
        "test -f ${local.vmware_output_path}/${local.vm_name}.vmdk || exit 1",
        "echo 'VMDK conversion complete'",
        "# Delete qcow2 to save space",
        "rm -f ${local.vmware_packer_output}/${local.vm_name}.qcow2"
      ]
    }

    # Step 2: Register VMDK as artifact
    post-processor "artifice" {
      files = [
        "${local.vmware_output_path}/${local.vm_name}.vmdk"
      ]
      keep_input_artifact = false
    }

    # Step 3: Generate VMware OVF file
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Generating VMware OVF descriptor...'",
        "cd ${local.vmware_output_path}",
        <<-EOT
        cat > ${local.vm_name}.ovf <<'OVFEOF'
        ${templatefile("templates/vmware.ovf.pkrtpl.hcl", {
          vm_name      = local.vm_name
          vm_disk_size = var.vm_disk_size
          vm_cpu_core  = var.vm_cpu_core
          vm_mem_size  = var.vm_mem_size
        })}
        OVFEOF
        EOT
        ,
        "test -f ${local.vm_name}.ovf || exit 1",
        "echo 'OVF descriptor created successfully'"
      ]
    }

    # Step 4: Create VMware/vSphere OVA (tar of OVF+VMDK)
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Creating VMware OVA archive...'",
        "cd ${local.vmware_output_path}",
        "tar -cf ${local.vm_name}.ova ${local.vm_name}.ovf ${local.vm_name}.vmdk",
        "test -f ${local.vm_name}.ova || exit 1",
        "echo 'OVA archive created: ${local.vm_name}.ova'",
        "# Keep OVA and delete separate OVF/VMDK to save space",
        "rm -f ${local.vm_name}.ovf ${local.vm_name}.vmdk"
      ]
    }

    # Step 5: Register OVA as artifact
    post-processor "artifice" {
      files = [
        "${local.vmware_output_path}/${local.vm_name}.ova"
      ]
      keep_input_artifact = true
    }

    # Step 6: Create Vagrant VMware .box file
    post-processor "shell-local" {
      inline = [
        "set -e",
        "echo 'Creating Vagrant VMware box...'",
        "mkdir -p ${local.vagrant_output_path}/temp-vmware",
        "# Extract OVA to get OVF and VMDK for Vagrant box",
        "tar -xf ${local.vmware_output_path}/${local.vm_name}.ova -C ${local.vagrant_output_path}/temp-vmware",
        "cd ${local.vagrant_output_path}/temp-vmware",
        "test -f ${local.vm_name}.ovf || exit 1",
        "test -f ${local.vm_name}.vmdk || exit 1",
        "# Create VMX file from OVF for Vagrant",
        "mv ${local.vm_name}.ovf ${local.vm_name}.vmx",
        "echo '{\"provider\":\"vmware_desktop\"}' > metadata.json",
        "tar czf ../${local.vm_name}-vmware.box *",
        "test -f ../${local.vm_name}-vmware.box || exit 1",
        "echo 'Vagrant box created: ${local.vm_name}-vmware.box'",
        "cd ..",
        "rm -rf temp-vmware"
      ]
    }
  }
}
