variable "vm_name" {
  description = "Name of the virtual machine"
  type        = string
}

variable "box_file" {
  description = "Path to the Vagrant box file (generated by Packer)"
  type        = string
}

variable "cpus" {
  description = "Number of CPU cores"
  type        = number
  default     = 3
}

variable "memory" {
  description = "Memory size in MB"
  type        = number
  default     = 8192
}

variable "bridged_adapter" {
  description = "Network interface to bridge to"
  type        = string
  default     = "pentap0"
}

variable "vram" {
  description = "Video memory in MB"
  type        = number
  default     = 256
}

variable "graphics_controller" {
  description = "Graphics controller type"
  type        = string
  default     = "vmsvga"
}

variable "clipboard_mode" {
  description = "Clipboard sharing mode"
  type        = string
  default     = "bidirectional"
}

variable "env" {
  description = "Environment name (dev, prod, etc.)"
  type        = string
  default     = "dev"
}

variable "run_post_deploy" {
  description = "Run post-deployment Ansible configuration automatically"
  type        = bool
  default     = false
}

variable "post_deploy_script" {
  description = "Path to post-deployment script"
  type        = string
  default     = ""
}
