---
- name: Kali provisioning initialization
  hosts: default
  become_method: ansible.builtin.sudo

  vars_files:
    - ../inventory/group_vars/all/vault.yml
    - ../vars/user_setup.yml

  roles:
    - pluggero.user_setup
