---
- name: VMware tools provisioning
  hosts: default
  become_method: ansible.builtin.sudo

  vars_files:
    - ../inventory/group_vars/all/vault.yml

  roles: []

- name: Import workarounds playbook
  ansible.builtin.import_playbook: provision-workarounds.yml
