---
- name: Kali provisioning initialization
  hosts: default
  become_method: ansible.builtin.sudo

  vars_files:
    - ../inventory/group_vars/all/vault.yml

  vars:
    user_setup_users:
      - name: "{{ ansible_user }}"
        shell: "/bin/bash"
        groups: []
        groups_append: true
        env_var_setup: false
        env_var_file: ".env_vars"
        user_directory_setup: true
        user_directories:
          - name: ".local/share/archive"
            env_var: "XDG_ARCHIVE_DIR"
          - name: ".config"
            env_var: "XDG_CONFIG_DIR"
          - name: "desktop"
            env_var: "XDG_DESKTOP_DIR"
          - name: "documents"
            env_var: "XDG_DOCUMENTS_DIR"
          - name: "downloads"
            env_var: "XDG_DOWNLOAD_DIR"
          - name: "music"
            env_var: "XDG_MUSIC_DIR"
          - name: "pictures"
            env_var: "XDG_PICTURES_DIR"
          - name: "tools"
            env_var: "XDG_TOOLS_DIR"
          - name: "videos"
            env_var: "XDG_VIDEOS_DIR"
        ssh_setup: true
        ssh_directory: ".ssh"
        ssh_public_keys: "{{ user_setup_ssh_public_keys | default([]) }}"
        password: "{{ user_setup_password | password_hash('sha512', user_setup_password_salt) }}"

  roles:
    - pluggero.user_setup
